### ISSUE TITLE
"Error: invalid BigNumber value" when deploying on Ubuntu

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iott-dapp-example#2]
Running the deployment script on Ubuntu, it does not complete and stops with the errors below:

```bash
$ npx hardhat run scripts/1_deploy.ts --network testnet

✖ Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true
APP_CONTRACT=0xa56873c08638c4c326099837e6f9095AeC607a24
BANK_CONTRACT=0xac9544c9285Ab525C77e5B75Ee34273691701878
REGISTRATION_CONTRACT=0xB97c82D08f7eB0A8154D7E1CA34f241DEA722e77
PEBBLE_CONTRACT=0x352E533B4bB814B5Bb94B45D6bA939747D62bb01
ACCOUNT_CONTRACT=0xfedbEA4d9fe869Eee5a25A863f715Df1697D3ef8
{ Error: invalid BigNumber value (argument="value", value="52b7d2dcc80cd2e4000000", code=INVALID_ARGUMENT, version=bignumber/5.3.0)
    at Logger.makeError (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Logger.throwArgumentError (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:229:21)
    at Function.BigNumber.from (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:291:23)
    at NumberCoder.encode (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/abi/src.ts/coders/number.ts:25:27)
    at /home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/abi/src.ts/coders/array.ts:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
    at TupleCoder.encode (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:54:16)
    at AbiCoder.encode (/home/oem/Source/github/iotexproject/iott-dapp-example-main/contracts/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:112:15)
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: <BN: 52b7d2dcc80cd2e4000000> }
```

**Comment by raullenchai** [comment]
Same error when deploy using macos

```
rc7@raullens-mbp contracts % npx hardhat run scripts/1_deploy.ts --network testnet
APP_CONTRACT=0xB20294968665037cAc13bCc3feeA77403c7a3EbA
BANK_CONTRACT=0x15d910612A5C212f2bF2ad691803ac3F0439eE46
REGISTRATION_CONTRACT=0xbD7710674Aa7A45D156Ae6d639dF32F6a691Cd23
PEBBLE_CONTRACT=0xd05a9cD1b1c3CFc694C7e2E80e5E0975B5204691
ACCOUNT_CONTRACT=0x9796f0b790F2E2F6aF3A2eca518B9ced08DB9804
Error: invalid BigNumber value (argument="value", value="52b7d2dcc80cd2e4000000", code=INVALID_ARGUMENT, version=bignumber/5.3.0)
    at Logger.makeError (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Logger.throwArgumentError (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:229:21)
    at Function.BigNumber.from (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:291:23)
    at NumberCoder.encode (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/abi/src.ts/coders/number.ts:25:27)
    at /Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/abi/src.ts/coders/array.ts:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
    at TupleCoder.encode (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:54:16)
    at AbiCoder.encode (/Users/rc7/work/src/github.com/iotexproject/iott-dapp-example/contracts/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:112:15) {
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: BN {
    negative: 0,
    words: [ 0, 33764537, 58535372, 330 ],
    length: 4,
    red: null
  }
}
```

**Comment by raullenchai** [comment]
https://github.com/iotexproject/iott-dapp-example/commit/aa20ff88db2dcf3d8a313600a16c27bf91d13d58
